networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    restart: unless-stopped
    # Mapeamos 5335 fuera al 5335 dentro para que coincidan
    ports:
      - "5335:5335/udp"
      - "5335:5335/tcp"
    networks:
      dns_net:
        ipv4_address: 172.20.0.5
    volumes:
      # AQUI ESTABA EL ERROR: La ruta correcta es /etc/unbound/...
      - "./unbound/unbound.conf:/etc/unbound/unbound.conf"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD=admin
      - PIHOLE_DNS_=172.20.0.5#5335
      - DNSMASQ_LISTENING=all   <-- Â¡ESTA ES LA NUEVA!
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      - dns_net
    depends_on:
      - unbound
