services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      DNSMASQ_LISTENING: all
      # Contrase√±a por defecto para el panel (que la cambien luego):
      WEBPASSWORD: 'admin'
      # Le decimos a Pi-hole que use nuestro Unbound como DNS:
      PIHOLE_DNS_: '172.20.0.5#5335'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 172.20.0.2

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    volumes:
      - './unbound:/opt/unbound/etc/unbound'
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 172.20.0.5

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
